name: Deploy

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]
  push:
    tags: [ v* ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.ref_type == 'tag' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_BASE_URL=${{ github.ref_type == 'tag' && 'https://automation.getmentore.com' }}
            NEXT_PUBLIC_API_BASE_URL=${{ github.ref_type == 'tag' && 'https://automation.getmentore.com' }}
            NEXT_PUBLIC_SOCKET_URL=http://3.109.32.206:3002
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
